### ISSUE TITLE
pthread_rwlock_unlock on unlocked rwlock causes undefined behaviour, or illegal instruction

### ISSUE THREAD

**Issue by asantoni** [karlheyes/icecast-kh#157]
I just witnessed an Icecast-kh 2.4.0-kh3 crash, and grabbed a backtrace:

`Reading symbols from /usr/bin/icecast2...done.
[New LWP 19048]
[New LWP 29164]
[New LWP 19047]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/bin/icecast -b -c /etc/icecast2/icecast.xml'.
Program terminated with signal SIGILL, Illegal instruction.
#0  0x00007f6310b1cedc in _xend () at pthread_rwlock_unlock.c:38
38      pthread_rwlock_unlock.c: No such file or directory.
[Current thread is 1 (Thread 0x7f6308d31700 (LWP 19048))]
(gdb) bt
#0  0x00007f6310b1cedc in _xend () at pthread_rwlock_unlock.c:38
#1  __GI___pthread_rwlock_unlock (rwlock=rwlock@entry=0x7f63061b24c8) at pthread_rwlock_unlock.c:38
#2  0x0000000000435f62 in thread_rwlock_unlock_c (rwlock=rwlock@entry=0x7f63061b24c8, line=line@entry=1118, file=file@entry=0x43d32b "source.c") at thread.c:590
#3  0x0000000000416c7b in send_to_listener (client=0x7f62fc046820) at source.c:1118
#4  0x000000000041b91b in worker (arg=arg@entry=0x135cc00) at client.c:700
#5  0x00000000004364ab in _start_routine (arg=0x135ccc0) at thread.c:700
#6  0x00007f6310b176ba in start_thread (arg=0x7f6308d31700) at pthread_create.c:333
#7  0x00007f631084d82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

(gdb) thread apply all bt

Thread 3 (Thread 0x7f6311bca740 (LWP 19047)):
#0  0x00007f6310b20c1d in nanosleep () at ../sysdeps/unix/syscall-template.S:84
#1  0x0000000000436006 in thread_sleep (len=len@entry=1000000) at thread.c:660
#2  0x0000000000411b23 in _slave_thread () at slave.c:1207
#3  slave_initialize () at slave.c:240
#4  0x000000000040915e in server_process () at main.c:238
#5  0x000000000040517d in main (argc=4, argv=0x7ffee8ba94f8) at main.c:437

Thread 2 (Thread 0x7f6308b30700 (LWP 29164)):
#0  0x00007f6310841b5d in poll () at ../sysdeps/unix/syscall-template.S:84
#1  0x000000000040c743 in poll (__timeout=4000, __nfds=<optimized out>, __fds=0x7f6308b2fc30) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  wait_for_serversock () at connection.c:874
#3  accept_client () at connection.c:979
#4  connection_thread (arg=arg@entry=0x0) at connection.c:1360
#5  0x00000000004364ab in _start_routine (arg=0x1534b30) at thread.c:700
#6  0x00007f6310b176ba in start_thread (arg=0x7f6308b30700) at pthread_create.c:333
#7  0x00007f631084d82d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
`

I suspect what's happened is that pthread_rwlock_unlock() was called on a rwlock that was already unlocked, which causes 'undefined behaviour'. It turns out on Intel's Haswell architecture, this causes an illegal instruction. Fun times! The machine was running Ubuntu 16.04 and icecast-kh 2.4.0-kh3 was compiled on the same hardware/OS as that machine.

Intel generously provides a workaround to prevent this type of bug from crashing an application, but it'd be better to try to prevent the double unlock from happening in the first place: https://github.com/andikleen/tsx-tools/blob/master/ignore-xend.c

Other info:
- https://sourceware.org/bugzilla/show_bug.cgi?id=17561

This crash occurred on a fairly loaded server, if that helps. I have a full crash dump that I can provide to you if needed.

Thanks!

**Comment by karlheyes** [comment]
hmm, I thought I had caught all the ways that could of happened.  Can you get me the log leading up to that, if the core is available then great (but provide the icecast binary as well).

karl.

**Comment by asantoni** [comment]
Hi Karl, I've sent you the crash dump, icecast binary, and log snippet by email. Thanks!

**Comment by karlheyes** [comment]
there is defintely a memory corruption occurring with that core, and it looks like a client was getting some service when it should not of, on a stream that had terminated and cleaned up.  The extra unlock that occurs triggering the fault is not surprising in such cases.

The issue then is what causes the original corruption. You should try the updated kh5 to make sure some of the existing race fixes are not a cause. 

karl
