### ISSUE TITLE
Icecast crash on 2.4.0-kh5: Segmentation fault

### ISSUE THREAD

**Issue by yarik2720** [karlheyes/icecast-kh#161]
If any user trying to access icecast server with https adress, for example https://domain.net:8000, server crashes.
kern.log:
`May 17 22:49:11 ns349384 kernel: icecast[4423]: segfault at 8 ip 00006d9f3a7e18a1 sp 00006d9f3396dd20 error 4 in libssl.so.1.0.0[6d9f3a7a7000+55000]
May 17 22:49:11 ns349384 kernel: grsec: From 127.0.0.6: Segmentation fault occurred at 0000000000000008 in /usr/local/bin/icecast[icecast:4423] uid/euid:1001/1001 gid/egid:1001/1001, parent /sbin/init[init:1] uid/euid:0/0 gid/egid:0/0`
Ubuntu 14.04.5

**Comment by karlheyes** [comment]
ok, lets see what you are dong to trigger this. How easy is ti to trigger?

If it's most of the time, then can you trap it in gdb,   gdb --args icecast -c icecast.xml 
> run
trigger and report what you see.

karl.

**Comment by yarik2720** [comment]
Here is output:
```
(gdb) run
Starting program: /usr/local/bin/icecast -c /usr/local/share/icecast/icecast.xml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Changed supplementary groups based on user: icecast.
Changed groupid to 1001.
Changed userid to 1001.
[New Thread 0x78ecf8b79700 (LWP 11153)]
[New Thread 0x78ecf8968700 (LWP 11154)]
[New Thread 0x78ecf86af700 (LWP 11155)]
[New Thread 0x78ecf83e2700 (LWP 11156)]
[New Thread 0x78ecebf94700 (LWP 11157)]
[New Thread 0x78ecebb70700 (LWP 11159)]
[New Thread 0x78ecebd89700 (LWP 11158)]
[Thread 0x78ecebd89700 (LWP 11158) exited]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x78ecf83e2700 (LWP 11156)]
0x000078ecff4d48a1 in SSL_set_accept_state () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
(gdb) bt
#0  0x000078ecff4d48a1 in SSL_set_accept_state () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
#1  0x000000000040c6ec in connection_uses_ssl (con=0x78ecd8000ca0) at connection.c:720
#2  0x000000000040c7ac in connection_peek (con=con@entry=0x78ecd8000ca0) at connection.c:738
#3  0x000000000040c9f9 in http_client_request (client=0x78ecd8000c60) at connection.c:1091
#4  0x000000000041d71f in worker (arg=arg@entry=0x36edcc0) at client.c:706
#5  0x0000000000437995 in _start_routine (arg=0x36ed900) at thread.c:708
#6  0x000078ecfe267184 in start_thread (arg=0x78ecf83e2700) at pthread_create.c:312
#7  0x000078ecfdf94bed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111

```
```
(gdb) bt full
#0  0x000078ecff4d48a1 in SSL_set_accept_state () from /lib/x86_64-linux-gnu/libssl.so.1.0.0
No symbol table info available.
#1  0x000000000040c6ec in connection_uses_ssl (con=0x78ecd8000ca0) at connection.c:720
No locals.
#2  0x000000000040c7ac in connection_peek (con=con@entry=0x78ecd8000ca0) at connection.c:738
        arr = "\026\003\001\000\301\001\000\000\275\003\003\002\222i\\\376ɓ\261%"
        r = <optimized out>
        __func__ = "connection_peek"
#3  0x000000000040c9f9 in http_client_request (client=0x78ecd8000c60) at connection.c:1091
        buf = 0x78ecd8000dc0 "\230\006"
        refbuf = 0x78ecd8001dd0
        remaining = 4095
        ret = -1
        __func__ = "http_client_request"
#4  0x000000000041d71f in worker (arg=arg@entry=0x36edcc0) at client.c:706
        ret = 0
        nx = 0x0
        process = 1
        client = 0x78ecd8000c60
        sched_ms = 1495476863985
        worker = 0x36edcc0
        prev_count = 1
        prevp = 0x78ecd8000b68
        c = 1
        __func__ = "worker"
#5  0x0000000000437995 in _start_routine (arg=0x36ed900) at thread.c:708
        start = 0x36ed900
        start_routine = 0x41d630 <worker>
        real_arg = 0x36edcc0
        thread = 0x36edd40
#6  0x000078ecfe267184 in start_thread (arg=0x78ecf83e2700) at pthread_create.c:312
        __res = <optimized out>
        pd = 0x78ecf83e2700
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {132959172437760, 730494224329882744, 1, 0, 132959172438464, 132959172437760, -289693979364541320, -289707103798281096},
              mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
---Type <return> to continue, or q <return> to quit---
        not_first_call = <optimized out>
        pagesize_m1 = <optimized out>
        sp = <optimized out>
        freesize = <optimized out>
        __PRETTY_FUNCTION__ = "start_thread"
#7  0x000078ecfdf94bed in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
No locals.

```

**Comment by karlheyes** [comment]
dumb bug on my part.   This should be fixed on the master tree.

karl.

**Comment by karlheyes** [comment]
kh6 is now out.

karl.

**Comment by yarik2720** [comment]
@karlheyes updated to kh6, thanks, issue now fixed
