### ISSUE TITLE
Segfault when adding http-headers on Debian

### ISSUE THREAD

**Issue by glitch59** [karlheyes/icecast-kh#383]
Hi Karl,

After upgrading to icecast-2.4.0-kh17 we get a SEGFAULT when we start Icecast.
The segfault only  happens when we add the following code to our icecast.xml file:
```
<http-headers>
    <header name="Access-Control-Allow-Origin" value="*"/>
</http-headers>
```
The following data is logged:
```
[Wed Jan 18 11:54:24 2023] icecast[4163168]: segfault at 0 ip 00005613650b4697 sp 00007ffe4c6b7540 error 4 in icecast[5613650b3000+40000]
[Wed Jan 18 11:54:24 2023] Code: ef ff 15 f4 8a 05 00 48 83 c4 50 44 89 e0 5b 5d 41 5c 41 5d 41 5e c3 0f 1f 40 00 41 bc ff ff ff ff eb e4 41 54 49 89 f4 55 53 <48> 8b 1f 48 85 db 0f 84 50 01 00 00 48 8b 6e 18 eb 12 0f 1f 80 00
```

When we remove the http-headers section, the server starts and responds without any issues.

We are running it on Debian: 
`Linux 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux`

Grt Sven.

**Comment by karlheyes** [comment]
I've just tried that snippet in a blank mount here and it works.  do you have anything else to expand on it.

maybe copy just that mount to a new xml, see if that faults with the headers and then get a backtrace from a debug build ie make debug, run gdb --args .../icecast --c new.xml , trigger the crash, the send the bt output.

karl

**Comment by glitch59** [comment]
As requested: 

```
root@2f0e7a280d42:/srv/backup/icecast# gdb --args icecast -c new.xml
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from icecast...
(gdb) run
Starting program: /usr/local/bin/icecast -c new.xml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555555b697 in _add_http_header (top=top@entry=0x0, src=src@entry=0x7fffffffd700) at cfgfile.c:1160
1160        ice_config_http_header_t **trail = top, *hdr = *top;

```

**Comment by karlheyes** [comment]
can you run bt in that gdb. the deref looks to be problem.

karl

**Comment by glitch59** [comment]
Ah sorry, first time using gdb, here you go:
```
root@2f0e7a280d42:/srv/backup/icecast# gdb --args icecast -c new.xml
GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from icecast...
(gdb) run
Starting program: /usr/local/bin/icecast -c new.xml
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
0x000055555555b697 in _add_http_header (top=top@entry=0x0, src=src@entry=0x7fffffffd700) at cfgfile.c:1160
1160        ice_config_http_header_t **trail = top, *hdr = *top;
(gdb) bt
#0  0x000055555555b697 in _add_http_header (top=top@entry=0x0, src=src@entry=0x7fffffffd700) at cfgfile.c:1160
#1  0x000055555555d70c in config_get_http_header (cfg=<optimized out>, arg=0x0) at cfgfile.c:1227
#2  0x000055555555bf9a in parse_xml_tags (cfg=<optimized out>, args=args@entry=0x7fffffffd850) at cfgfile.c:341
#3  0x000055555555d4ff in _parse_http_headers (cfg=<optimized out>, arg=<optimized out>) at cfgfile.c:1263
#4  0x000055555555bf9a in parse_xml_tags (cfg=cfg@entry=0x7fffffffddd0, args=args@entry=0x7fffffffd930) at cfgfile.c:341
#5  0x000055555555e1e1 in _parse_root (cfg=cfg@entry=0x7fffffffddd0, p=0x0) at cfgfile.c:1803
#6  0x000055555555ecf4 in config_parse_file (filename=filename@entry=0x7fffffffde20 "new.xml", configuration=configuration@entry=0x5555555b41e0 <_current_configuration>) at cfgfile.c:674
#7  0x000055555555ed5c in config_initial_parse_file (filename=filename@entry=0x7fffffffde20 "new.xml") at cfgfile.c:640
#8  0x0000555555560760 in server_init (argc=argc@entry=3, argv=argv@entry=0x7fffffffe568) at main.c:371
#9  0x000055555555b13b in main (argc=3, argv=0x7fffffffe568) at main.c:435

```

**Comment by karlheyes** [comment]
just for reference, the bug was on the global headers, not mount.  It's now fixed anyway
